
from enigma.constants import MENU as M

BASIC_3CH = {
    0: {M.IN: 'B',
        M.OUT: 'A',
        M.LINK: 'ZZZ',
        M.CONXNS: {M.IN: {1: M.OUT, 3: M.IN}, M.OUT: {2: M.IN}}},
    2: {M.IN: 'A',
        M.OUT: 'C',
        M.LINK: 'ZZB',
        M.CONXNS: {M.IN: {0: M.OUT}, M.OUT: {1: M.IN}}},
    1: {M.IN: 'C',
        M.OUT: 'B',
        M.LINK: 'ZZA',
        M.CONXNS: {M.IN: {2: M.OUT}, M.OUT: {0: M.IN, 3: M.IN}}},
    3: {M.IN: 'B',
        M.OUT: 'D',
        M.LINK: 'ZZC',
        M.CONXNS: {M.IN: {0: M.IN, 1: M.OUT}, M.OUT: {4: M.IN}}},
    4: {M.IN: 'D',
        M.OUT: 'E',
        M.LINK: 'ZZD',
        M.CONXNS: {M.IN: {3: M.OUT}, M.OUT: {}}},
    M.CONFIG: {M.TEST_CHAR: 'B',
               M.LINK: 'QQQ',
               M.IN: 'B',
               M.OUT: 'B',
               M.CONXNS: {M.IN: {0: M.IN, 1: M.OUT, 3: M.IN},
                          M.OUT: {0: M.IN, 1: M.OUT, 3: M.IN}}}
}

BASIC_4CH = {
    0: {M.CONXNS: {M.IN: {2: M.IN, 5: M.OUT}, M.OUT: {1: M.IN}},
        M.IN: 'B',
        M.LINK: 'ZZZ',
        M.OUT: 'C'},
    1: {M.IN: 'C',
        M.OUT: 'A',
        M.LINK: 'ZZA',
        M.CONXNS: {M.IN: {0: M.OUT}, M.OUT: {}}},
    2: {M.CONXNS: {M.IN: {0: M.IN, 5: M.OUT}, M.OUT: {3: M.IN}},
        M.IN: 'B',
        M.LINK: 'ZZB',
        M.OUT: 'D'},
    3: {M.CONXNS: {M.IN: {2: M.OUT}, M.OUT: {4: M.IN}},
        M.IN: 'D',
        M.LINK: 'ZZC',
        M.OUT: 'E'},
    4: {M.CONXNS: {M.IN: {3: M.OUT}, M.OUT: {5: M.IN}},
        M.IN: 'E',
        M.LINK: 'ZZD',
        M.OUT: 'F'},
    5: {M.CONXNS: {M.IN: {4: M.OUT}, M.OUT: {0: M.IN, 2: M.IN}},
        M.IN: 'F',
        M.LINK: 'ZZE',
        M.OUT: 'B'},
    M.CONFIG: {M.CONXNS: {M.IN: {0: M.IN, 2: M.IN, 5: M.OUT},
                          M.OUT: {0: M.IN, 2: M.IN, 5: M.OUT}},
               M.IN: 'B',
               M.LINK: 'QQQ',
               M.OUT: 'B',
               M.TEST_CHAR: 'B'}}

WELCHMAN_1L = {
    0: {M.CONXNS: {M.IN: {2: M.OUT, 13: M.IN}, M.OUT: {}},
        M.IN: 'T',
        M.LINK: 'ZZZ',
        M.OUT: 'C'},
    2: {M.CONXNS: {M.IN: {12: M.OUT}, M.OUT: {0: M.IN, 13: M.IN}},
        M.IN: 'N',
        M.LINK: 'ZZB',
        M.OUT: 'T'},
    4: {M.CONXNS: {M.IN: {7: M.IN, 10: M.IN, 11: M.IN},
                   M.OUT: {5: M.IN, 9: M.OUT}},
        M.IN: 'E',
        M.LINK: 'ZZD',
        M.OUT: 'P'},
    5: {M.CONXNS: {M.IN: {4: M.OUT, 9: M.OUT}, M.OUT: {}},
        M.IN: 'P',
        M.LINK: 'ZZE',
        M.OUT: 'V'},
    7: {M.CONXNS: {M.IN: {4: M.IN, 10: M.IN, 11: M.IN},
                   M.OUT: {9: M.IN, 12: M.IN}},
        M.IN: 'E',
        M.LINK: 'ZZG',
        M.OUT: 'I'},
    9: {M.CONXNS: {M.IN: {7: M.OUT, 12: M.IN}, M.OUT: {4: M.OUT, 5: M.IN}},
        M.IN: 'I',
        M.LINK: 'ZZI',
        M.OUT: 'P'},
    10: {M.CONXNS: {M.IN: {4: M.IN, 7: M.IN, 11: M.IN}, M.OUT: {}},
         M.IN: 'E',
         M.LINK: 'ZZJ',
         M.OUT: 'D'},
    11: {M.CONXNS: {M.IN: {4: M.IN, 7: M.IN, 10: M.IN}, M.OUT: {}},
         M.IN: 'E',
         M.LINK: 'ZZK',
         M.OUT: 'U'},
    12: {M.CONXNS: {M.IN: {7: M.OUT, 9: M.IN}, M.OUT: {2: M.IN}},
         M.IN: 'I',
         M.LINK: 'ZZL',
         M.OUT: 'N'},
    13: {M.CONXNS: {M.IN: {0: M.IN, 2: M.OUT}, M.OUT: {}},
         M.IN: 'T',
         M.LINK: 'ZZM',
         M.OUT: 'K'},
    M.CONFIG: {M.CONXNS: {M.IN: {4: M.IN, 7: M.IN, 10: M.IN, 11: M.IN},
                          M.OUT: {4: M.IN, 7: M.IN, 10: M.IN, 11: M.IN}},
               M.IN: 'E',
               M.LINK: 'QQQ',
               M.OUT: 'E',
               M.TEST_CHAR: 'E'}}


class BOMBE_TEST1:
    left_rotor = 'I'
    middle_rotor = 'II'
    right_rotor = 'III'
    reflector = 'B'
    current_window_3 = 'ABC'
    ring_settings_3 = 'GHI'
    crib = "EARTHVENUSMARSSATURN"
    cypher = "AOOOBUMAAJJIDEHNKZPP"
    menu = {0: {'conxns': {'in': {6: 'in', 13: 'out'},
                'out': {1: 'in', 7: 'out', 8: 'out', 11: 'in', 15: 'in'}},
                'in': 'E',
                'menu_link': 'ZZZ',
                'out': 'A'},
            1: {'conxns': {'in': {0: 'out', 7: 'out', 8: 'out', 11: 'in', 15: 'in'},
                'out': {2: 'out', 3: 'out'}},
                'in': 'A',
                'menu_link': 'ZZA',
                'out': 'O'},
            2: {'conxns': {'in': {12: 'in', 18: 'in'}, 'out': {1: 'out', 3: 'out'}},
            'in': 'R',
                'menu_link': 'ZZB',
                'out': 'O'},
            3: {'conxns': {'in': {16: 'in'}, 'out': {1: 'out', 2: 'out'}},
            'in': 'T',
                'menu_link': 'ZZC',
                'out': 'O'},
            4: {'conxns': {'in': {14: 'out'}, 'out': {}},
            'in': 'H',
                'menu_link': 'ZZD',
                'out': 'B'},
            5: {'conxns': {'in': {}, 'out': {8: 'in', 17: 'in'}},
            'in': 'V',
                'menu_link': 'ZZE',
                'out': 'U'},
            6: {'conxns': {'in': {0: 'in', 13: 'out'}, 'out': {10: 'in'}},
            'in': 'E',
                'menu_link': 'ZZF',
                'out': 'M'},
            7: {'conxns': {'in': {15: 'out', 19: 'in'},
                           'out': {0: 'out', 1: 'in', 8: 'out', 11: 'in', 15: 'in'}},
            'in': 'N',
                'menu_link': 'ZZG',
                'out': 'A'},
            8: {'conxns': {'in': {5: 'out', 17: 'in'},
                           'out': {0: 'out', 1: 'in', 7: 'out', 11: 'in', 15: 'in'}},
            'in': 'U',
                'menu_link': 'ZZH',
                'out': 'A'},
            9: {'conxns': {'in': {13: 'in', 14: 'in'}, 'out': {10: 'out'}},
            'in': 'S',
                'menu_link': 'ZZI',
                'out': 'J'},
            10: {'conxns': {'in': {6: 'out'}, 'out': {9: 'out'}},
                 'in': 'M',
                 'menu_link': 'ZZJ',
                 'out': 'J'},
            11: {'conxns': {'in': {0: 'out', 1: 'in', 7: 'out', 8: 'out', 15: 'in'},
                            'out': {}},
                 'in': 'A',
                 'menu_link': 'ZZK',
                 'out': 'I'},
            12: {'conxns': {'in': {2: 'in', 18: 'in'}, 'out': {}},
                 'in': 'R',
                 'menu_link': 'ZZL',
                 'out': 'D'},
            13: {'conxns': {'in': {9: 'in', 14: 'in'}, 'out': {0: 'in', 6: 'in'}},
                 'in': 'S',
                 'menu_link': 'ZZM',
                 'out': 'E'},
            14: {'conxns': {'in': {9: 'in', 13: 'in'}, 'out': {4: 'in'}},
                 'in': 'S',
                 'menu_link': 'ZZN',
                 'out': 'H'},
            15: {'conxns': {'in': {0: 'out', 1: 'in', 7: 'out', 8: 'out', 11: 'in'},
                            'out': {7: 'in', 19: 'in'}},
                 'in': 'A',
                 'menu_link': 'ZZO',
                 'out': 'N'},
            16: {'conxns': {'in': {3: 'in'}, 'out': {}},
                 'in': 'T',
                 'menu_link': 'ZZP',
                 'out': 'K'},
            17: {'conxns': {'in': {5: 'out', 8: 'in'}, 'out': {}},
                 'in': 'U',
                 'menu_link': 'ZZQ',
                 'out': 'Z'},
            18: {'conxns': {'in': {2: 'in', 12: 'in'}, 'out': {19: 'out'}},
                 'in': 'R',
                 'menu_link': 'ZZR',
                 'out': 'P'},
            19: {'conxns': {'in': {7: 'in', 15: 'out'}, 'out': {18: 'out'}},
                 'in': 'N',
                 'menu_link': 'ZZS',
                 'out': 'P'},
            'config': {'conxns': {'in': {0: 'out',
                                         1: 'in',
                                         7: 'out',
                                         8: 'out',
                                         11: 'in',
                                         15: 'in'},
                                  'out': {0: 'out',
                                          1: 'in',
                                          7: 'out',
                                          8: 'out',
                                          11: 'in',
                                          15: 'in'}},
                       'in': 'A',
                       'menu_link': 'QQQ',
                       'out': 'A',
                       'test_char': 'A'}}
