
from enigma.constants import MENU as M

BASIC_3CH = {
    0: {M.IN: 'B',
        M.OUT: 'A',
        M.LINK: 'ZZZ',
        M.CONXNS: {M.IN: {1: M.OUT, 3: M.IN}, M.OUT: {2: M.IN}}},
    2: {M.IN: 'A',
        M.OUT: 'C',
        M.LINK: 'ZZB',
        M.CONXNS: {M.IN: {0: M.OUT}, M.OUT: {1: M.IN}}},
    1: {M.IN: 'C',
        M.OUT: 'B',
        M.LINK: 'ZZA',
        M.CONXNS: {M.IN: {2: M.OUT}, M.OUT: {0: M.IN, 3: M.IN}}},
    3: {M.IN: 'B',
        M.OUT: 'D',
        M.LINK: 'ZZC',
        M.CONXNS: {M.IN: {0: M.IN, 1: M.OUT}, M.OUT: {4: M.IN}}},
    4: {M.IN: 'D',
        M.OUT: 'E',
        M.LINK: 'ZZD',
        M.CONXNS: {M.IN: {3: M.OUT}, M.OUT: {}}},
    M.CONFIG: {M.TEST_CHAR: 'B',
               M.LINK: 'QQQ',
               M.IN: 'B',
               M.OUT: 'B',
               M.CONXNS: {M.IN: {0: M.IN, 1: M.OUT, 3: M.IN},
                          M.OUT: {0: M.IN, 1: M.OUT, 3: M.IN}}}
}

BASIC_4CH = {
    0: {M.CONXNS: {M.IN: {2: M.IN, 5: M.OUT}, M.OUT: {}},
        M.IN: 'B',
        M.LINK: 'ZZZ',
        M.OUT: 'C'},
    2: {M.CONXNS: {M.IN: {0: M.IN, 5: M.OUT}, M.OUT: {3: M.IN}},
        M.IN: 'B',
        M.LINK: 'ZZB',
        M.OUT: 'D'},
    3: {M.CONXNS: {M.IN: {2: M.OUT}, M.OUT: {4: M.IN}},
        M.IN: 'D',
        M.LINK: 'ZZC',
        M.OUT: 'E'},
    4: {M.CONXNS: {M.IN: {3: M.OUT}, M.OUT: {5: M.IN}},
        M.IN: 'E',
        M.LINK: 'ZZD',
        M.OUT: 'F'},
    5: {M.CONXNS: {M.IN: {4: M.OUT}, M.OUT: {0: M.IN, 2: M.IN}},
        M.IN: 'F',
        M.LINK: 'ZZE',
        M.OUT: 'B'},
    M.CONFIG: {M.CONXNS: {M.IN: {0: M.IN, 2: M.IN, 5: M.OUT},
                          M.OUT: {0: M.IN, 2: M.IN, 5: M.OUT}},
               M.IN: 'B',
               M.LINK: 'QQQ',
               M.OUT: 'B',
               M.TEST_CHAR: 'B'}}

WELCHMAN_1L = {
    0: {M.CONXNS: {M.IN: {2: M.OUT, 13: M.IN}, M.OUT: {}},
        M.IN: 'T',
        M.LINK: 'ZZZ',
        M.OUT: 'C'},
    2: {M.CONXNS: {M.IN: {12: M.OUT}, M.OUT: {0: M.IN, 13: M.IN}},
        M.IN: 'N',
        M.LINK: 'ZZB',
        M.OUT: 'T'},
    4: {M.CONXNS: {M.IN: {7: M.IN, 10: M.IN, 11: M.IN},
                   M.OUT: {5: M.IN, 9: M.OUT}},
        M.IN: 'E',
        M.LINK: 'ZZD',
        M.OUT: 'P'},
    5: {M.CONXNS: {M.IN: {4: M.OUT, 9: M.OUT}, M.OUT: {}},
        M.IN: 'P',
        M.LINK: 'ZZE',
        M.OUT: 'V'},
    7: {M.CONXNS: {M.IN: {4: M.IN, 10: M.IN, 11: M.IN},
                   M.OUT: {9: M.IN, 12: M.IN}},
        M.IN: 'E',
        M.LINK: 'ZZG',
        M.OUT: 'I'},
    9: {M.CONXNS: {M.IN: {7: M.OUT, 12: M.IN}, M.OUT: {4: M.OUT, 5: M.IN}},
        M.IN: 'I',
        M.LINK: 'ZZI',
        M.OUT: 'P'},
    10: {M.CONXNS: {M.IN: {4: M.IN, 7: M.IN, 11: M.IN}, M.OUT: {}},
         M.IN: 'E',
         M.LINK: 'ZZJ',
         M.OUT: 'D'},
    11: {M.CONXNS: {M.IN: {4: M.IN, 7: M.IN, 10: M.IN}, M.OUT: {}},
         M.IN: 'E',
         M.LINK: 'ZZK',
         M.OUT: 'U'},
    12: {M.CONXNS: {M.IN: {7: M.OUT, 9: M.IN}, M.OUT: {2: M.IN}},
         M.IN: 'I',
         M.LINK: 'ZZL',
         M.OUT: 'N'},
    13: {M.CONXNS: {M.IN: {0: M.IN, 2: M.OUT}, M.OUT: {}},
         M.IN: 'T',
         M.LINK: 'ZZM',
         M.OUT: 'K'},
    M.CONFIG: {M.CONXNS: {M.IN: {4: M.IN, 7: M.IN, 10: M.IN, 11: M.IN},
                          M.OUT: {4: M.IN, 7: M.IN, 10: M.IN, 11: M.IN}},
               M.IN: 'E',
               M.LINK: 'QQQ',
               M.OUT: 'E',
               M.TEST_CHAR: 'E'}}
